import asyncio
import requests
import os
from dotenv import load_dotenv

# Load environment variables (like GOOGLE_API_KEY)
load_dotenv()

from google.adk.agents.llm_agent import Agent
from google.adk.tools import google_search
from google.adk.apps.app import App
from google.adk.runners import Runner
from google.adk.sessions.in_memory_session_service import InMemorySessionService
from google.genai import types

def send_push(message):
    """Sends a push notification via Pushover."""
    
    # Pushover APP TOKEN and USER KEY from .env file
    PUSHOVER_APP_TOKEN = os.getenv("PUSHOVER_APP_TOKEN") 
    PUSHOVER_USER_KEY = os.getenv("PUSHOVER_USER_KEY")

    try:
        response = requests.post(
            "https://api.pushover.net/1/messages.json",
            data={
                "token": PUSHOVER_APP_TOKEN,
                "user": PUSHOVER_USER_KEY,
                "message": message,
                "title": "🏎️ Daily Sports Update"
            }
        )
        response.raise_for_status() 
        print("✅ Push notification sent successfully!")
    except Exception as e:
        print(f"❌ Failed to send push notification: {e}")

# 1. Define the Agent
# We use gemini-2.5-flash which is a powerful and fast model
my_search_agent = Agent(
    model="gemini-2.5-flash",
    name='Jo_agent',
    description="Specialist in google search for sports updates",
    tools=[google_search],
)

# 2. Initialize the App
app = App(
    name="Jo_Sports_Update_App", 
    root_agent=my_search_agent
)

async def main():
    query = (
        "Gather the latest standings for:\n"
        "1. F1 Driver Standings\n"
        "2. F1 Constructor Standings\n"
        "3. IPL (Indian Premier League) Points Table\n"
        "4. NBA Standings (current season)\n\n"
        "Format the output to be very brief, use emojis, and be push-notification friendly. "
        "Summarize the top 3-5 only for each to keep it short."
    )
    
    # Initialize components to run the app
    session_service = InMemorySessionService()
    runner = Runner(app=app, session_service=session_service, auto_create_session=True)

    print("🚀 Agent is gathering the latest standings...")
    
    try:
        # Prepare the input message
        new_message = types.Content(
            parts=[types.Part(text=query)],
            role='user'
        )
        
        # Run the agent and process events
        responses = runner.run_async(
            user_id="cron_user",
            session_id="daily_update_session",
            new_message=new_message
        )
        
        final_message = ""
        async for event in responses:
            # ADK events contain content with parts
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        # Print thinking/partial output to console
                        print(part.text, end="", flush=True)
                        final_message += part.text
        
        final_message = final_message.strip()
        
        if final_message:
            print("\n\n--- Final Summary Sent ---")
            send_push(final_message)
        else:
            print("\n\n❌ No content was generated by the agent.")
            
    except Exception as e:
        print(f"\n\n❌ Execution failed: {e}")
        # For debugging:
        # import traceback
        # traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(main())