import asyncio
import argparse
import json
import os
from datetime import datetime, timezone
from dotenv import load_dotenv

load_dotenv()

from google.adk.agents.llm_agent import Agent
from google.adk.apps.app import App
from google.adk.runners import Runner
from google.adk.sessions.in_memory_session_service import InMemorySessionService
from google.genai import types

from tools_gmail import fetch_expense_emails
from tools_expenses import add_expense, get_monthly_summary, get_expense_categories

OUTPUT_FILE = os.getenv("OUTPUT_FILE", "output.json")

SYSTEM_PROMPT = """You are a personal expense-tracking assistant. Complete the following tasks:

TASK — EXPENSE TRACKING:
1. Call get_expense_categories() to know the valid categories.
2. Call fetch_expense_emails() to retrieve recent emails.
3. Review each email carefully. Only process emails that clearly represent a real financial transaction:
   - Receipts, invoices, order confirmations, payment confirmations
   - Skip newsletters, marketing emails, shipping notifications without a charge, or anything without a clear amount
4. For each genuine expense email, call add_expense() with:
   - msg_id: the email's "id" field (used for deduplication)
   - date: the transaction date in YYYY-MM-DD format
   - amount: numeric amount (no currency symbol)
   - currency: currency code (e.g. USD, EUR, GBP) — default to USD if unclear
   - vendor: the merchant/company name
   - category: one of the categories from get_expense_categories()
   - description: one short sentence describing the purchase
   - email_subject: the email subject line
5. Call get_monthly_summary() to retrieve the updated totals.

OUTPUT:
Produce a concise, friendly summary covering:
- How many new expenses were added today (and list them briefly)
- The monthly expense totals by category
- Any observations (e.g. biggest spend category, unusual charges)

Keep it clear and scannable. Use plain text with simple formatting."""


daily_agent = Agent(
    model="gemini-2.5-flash",
    name="daily_assistant_agent",
    description="Personal expense tracker that reads Gmail and categorizes expenses",
    tools=[fetch_expense_emails, add_expense, get_monthly_summary, get_expense_categories],
    instruction=SYSTEM_PROMPT,
)

app = App(name="Daily_Assistant_App", root_agent=daily_agent)


def _write_output(summary: str) -> None:
    from tools_expenses import _load
    store = _load()
    output = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "summary": summary,
        "expenses": {
            "new_today": [],
            "monthly_totals": store.get("monthly_totals", {}),
            "month_total": round(sum(store.get("monthly_totals", {}).values()), 2),
            "all_entries": store.get("expenses", []),
        },
    }
    with open(OUTPUT_FILE, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n✅ Output written to {OUTPUT_FILE}")


async def main():
    session_service = InMemorySessionService()
    runner = Runner(app=app, session_service=session_service, auto_create_session=True)

    message = types.Content(
        parts=[types.Part(text="Please run the expense tracking tasks now.")],
        role="user",
    )

    print("🚀 Daily assistant running...")

    final_message = ""
    try:
        responses = runner.run_async(
            user_id="cron_user",
            session_id="daily_assistant_session",
            new_message=message,
        )
        async for event in responses:
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        print(part.text, end="", flush=True)
                        final_message += part.text

        final_message = final_message.strip()
        if final_message:
            _write_output(final_message)
        else:
            print("\n❌ No output generated by the agent.")
    except Exception as e:
        print(f"\n❌ Execution failed: {e}")
        raise


def run_auth_flow():
    """One-time OAuth2 consent. Run this once from a machine with a browser."""
    from google_auth_oauthlib.flow import InstalledAppFlow

    SCOPES = ["https://www.googleapis.com/auth/gmail.readonly"]
    credentials_file = os.getenv("GOOGLE_CREDENTIALS_FILE", "credentials.json")
    token_file = os.getenv("GOOGLE_TOKEN_FILE", "token.json")

    if not os.path.exists(credentials_file):
        print(f"❌ credentials.json not found at '{credentials_file}'.")
        print("Download it from Google Cloud Console → APIs & Services → Credentials.")
        return

    flow = InstalledAppFlow.from_client_secrets_file(credentials_file, SCOPES)
    creds = flow.run_local_server(port=0)
    with open(token_file, "w") as f:
        f.write(creds.to_json())
    print(f"✅ Token saved to {token_file}. You can now run the agent headlessly.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Daily expense assistant")
    parser.add_argument(
        "--auth",
        action="store_true",
        help="Run one-time OAuth2 browser consent to generate token.json",
    )
    args = parser.parse_args()

    if args.auth:
        run_auth_flow()
    else:
        asyncio.run(main())
